# Generated by Django 4.1.6 on 2023-02-11 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dedektor', '0002_alter_kategorimodel_options_yazilarmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yazilarmodel',
            name='olusuturlma_tarihi',
        ),
        migrations.AddField(
            model_name='yazilarmodel',
            name='olusuturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
