# Generated by Django 4.1.6 on 2023-02-11 23:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedektor', '0003_remove_yazilarmodel_olusuturlma_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilarmodel',
            name='icerik',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
